import type { FinalizeContext, ScenarioSpec } from './types'
import { approvedCap, line } from './helpers'

export const airportPickup: ScenarioSpec = {
  id: 'airport-pickup',
  title: 'Airport Pickup',
  tagline: 'Coordinate a real-world, multi-party logistics chain — without overreach.',
  tools: [
    { name: 'Google Calendar', use: 'you stay until 5 PM' },
    { name: 'Flight tracker', use: 'track the SFO arrival' },
    { name: 'Uber · Lyft', use: 'book the ride', approval: true },
    { name: 'Snaplii wallet', use: 'pay for the ride', approval: true },
    { name: 'Contacts', use: 'your pickup person' },
    { name: 'Messages', use: 'share safety details', approval: true },
    { name: 'OpenTable', use: 'optional dinner after' },
  ],
  prompt:
    'I am at a hackathon that ends at 5 PM, but I need to pick someone up from the airport at 3 PM. I do not want to leave the event early. Arrange for an Uber from the airport to the hackathon location, share safety details with both of us, track the flight status, and help us plan dinner afterward if needed.',
  normalized_intent: 'Route an arriving guest from SFO to the hackathon by ride while you stay; share safety details; track flight; plan optional dinner.',
  user_goal: 'Solve a time/transport/safety conflict for you and another person without leaving your event — and without silent spending.',
  success_criteria: [
    'Flight status + arrival terminal tracked',
    'A ride from the airport to the venue prepared with cost + ETA',
    'Safety details prepared for both parties',
    'Optional dinner prepared',
  ],
  constraints: ['You stay at the event until 5 PM', 'Another person is involved — safety first', 'No silent spending'],
  time_window: 'Pickup ~3:00 PM; you stay until 5:00 PM',
  requested_capabilities: [
    'calendar.read',
    'location.read.current_event',
    'flight.search',
    'ride.estimate',
    'ride.booking.prepare',
    'contacts.read.limited',
    'messages.draft',
    'safety_share.prepare',
    'restaurant.search',
    'reservation.prepare',
  ],
  commit_capabilities: ['ride.booking.submit', 'messages.send', 'reservation.submit'],
  budget_limit: { amount: 80, currency: 'USD' },
  ttl_seconds: 5400,
  risk_level: 'high',
  fallback_plan:
    'Deny the ride and Passport keeps the prepared trip; you can book it yourself, or approve later. Safety details are only shared on a confirmed trip.',
  prevented: [
    'Booking a ride and authorizing payment without approval',
    'Sharing the other person’s details or your live location silently',
    'Messaging a real contact without approval',
    'Confirming a reservation you didn’t see',
  ],
  steps: [
    { kind: 'note', title: 'Classify the risk', description: 'Higher risk: this touches ride-hailing, payment, another person, and location. Every external step is gated.' },
    { kind: 'tool', title: 'Read current commitment', description: 'Confirm where you are and until when.', tool: 'location.current_event', input: {} },
    { kind: 'tool', title: 'Track the flight', description: 'Read flight status + arrival terminal.', tool: 'flight.status', input: { flight: 'UA 1882' } },
    { kind: 'tool', title: 'Estimate the ride', description: 'Price options from the terminal to the venue.', tool: 'ride.estimate', input: {} },
    { kind: 'tool', title: 'Read pickup contact (limited)', description: 'Read only the one contact being picked up.', tool: 'contacts.person', input: {} },
    { kind: 'tool', title: 'Prepare the ride', description: 'Build the ride request for review. Not booked.', tool: 'ride.prepare', input: { ride_id: 'ride_1' } },
    { kind: 'tool', title: 'Prepare safety share', description: 'Draft trip + driver details to share on a confirmed trip. No live sharing.', tool: 'safety.prepare', input: {} },
    { kind: 'tool', title: 'Draft a status note', description: 'Compose an update to the pickup person. Not sent.', tool: 'messages.draft', input: { to: 'Priya', body: 'On it — a car will meet you at SFO Terminal 3 ~3:05. I’ll send driver details once it’s confirmed.' } },
    { kind: 'tool', title: 'Find dinner options', description: 'Search restaurants near the venue.', tool: 'restaurant.search', input: {} },
    { kind: 'tool', title: 'Prepare a reservation', description: 'Draft a dinner reservation. Not confirmed.', tool: 'reservation.prepare', input: { restaurant_id: 'rest_3' } },
    {
      kind: 'approval',
      title: 'Book the ride',
      description: 'Book the Uber and authorize payment.',
      commitTool: 'ride.submit',
      commitInput: { product: 'UberX' },
      packet: {
        action_type: 'Book ride + authorize payment',
        description: 'Book UberX from SFO Terminal 3 to the hackathon (~$47, ETA 6 min) for Priya.',
        external_party: 'Uber · driver · Priya',
        estimated_cost: { amount: 47, currency: 'USD' },
        data_shared: ['Pickup terminal', 'Destination', 'Rider name'],
        irreversible: true,
        approve_button_label: 'Approve & book',
        deny_button_label: "Don't book",
        capability: 'ride.booking.submit',
      },
    },
    {
      kind: 'approval',
      title: 'Share safety details',
      description: 'Send driver + trip details to Priya.',
      commitTool: 'messages.send',
      commitInput: { to: 'Priya' },
      packet: {
        action_type: 'Share trip + safety details',
        description: 'Send driver name, plate, and a single-trip live ETA link to Priya.',
        external_party: 'Priya',
        estimated_cost: null,
        data_shared: ['Driver name & plate', 'Single-trip ETA link', 'Destination'],
        irreversible: true,
        approve_button_label: 'Share details',
        deny_button_label: "Don't share",
        capability: 'messages.send',
      },
    },
    {
      kind: 'approval',
      title: 'Confirm dinner',
      description: 'Confirm the drafted reservation.',
      commitTool: 'reservation.submit',
      commitInput: { restaurant: 'Marufuku Ramen' },
      packet: {
        action_type: 'Confirm reservation',
        description: 'Confirm a table for 2 at Marufuku Ramen at 7:30 PM.',
        external_party: 'Marufuku Ramen',
        estimated_cost: null,
        data_shared: ['Name', 'Party size', 'Time'],
        irreversible: false,
        approve_button_label: 'Confirm table',
        deny_button_label: 'Skip dinner',
        capability: 'reservation.submit',
      },
    },
  ],
  finalize(ctx: FinalizeContext) {
    return {
      title: 'Pickup coordinated',
      summary: 'Priya is routed from SFO to your event — you never had to leave.',
      lines: [
        line('Flight', 'UA 1882 JFK→SFO · on time · arr 14:48 · Terminal 3 F12', 'good'),
        line('Ride', approvedCap(ctx, 'ride.booking.submit') ? 'Booked (simulated) · UberX · ETA 6 min' : 'Prepared — not booked (~$47)', approvedCap(ctx, 'ride.booking.submit') ? 'good' : 'warn'),
        line('Safety', approvedCap(ctx, 'messages.send') ? 'Details shared (simulated)' : 'Drafted — not shared', approvedCap(ctx, 'messages.send') ? 'good' : 'warn'),
        line('Live location', 'Single-trip only — never continuous', 'good'),
        line('Dinner', approvedCap(ctx, 'reservation.submit') ? 'Confirmed (simulated) · Marufuku 7:30' : 'Drafted — not confirmed', approvedCap(ctx, 'reservation.submit') ? 'good' : 'warn'),
        line('You', 'Stayed at the event the whole time', 'good'),
      ],
      notes: [
        'Payment, messaging, and reservations each required a separate approval — nothing chained silently.',
        'Safety details were prepared but only shared on a trip you confirmed.',
      ],
    }
  },
}
