import type { FinalizeContext, ScenarioSpec } from './types'
import { approvedCap, line } from './helpers'

export const enrichMyLife: ScenarioSpec = {
  id: 'enrich-my-life',
  title: 'Enrich My Night',
  tagline: 'Plan a game night — order dinner, invite your friends, spoiler-safe and gated.',
  tools: [
    { name: 'Google Calendar', use: 'find a free evening this week', cap: 'calendar.write.commit', doneLabel: '✓ added' },
    { name: 'Sports schedule', use: 'kickoff time — spoiler-safe' },
    { name: 'YouTube TV', use: 'set up the replay, no score shown' },
    { name: 'DoorDash', use: 'order your usual', cap: 'delivery.order.submit', doneLabel: '✓ order placed' },
    { name: 'UberEats history', use: 'a backup food option' },
    { name: 'Snaplii wallet', use: 'pay for the order', approval: true, cap: 'delivery.order.submit', doneLabel: '✓ paid' },
    { name: 'Discord · Game Night', use: 'invite your friends', approval: true, cap: 'social.post.commit', doneLabel: '✓ shared' },
    { name: 'Reminders', use: 'so you never miss it', cap: 'reminders.write.commit', doneLabel: '✓ set' },
  ],
  prompt:
    'Plan a game night for me this week — find a free evening, set up the FIFA match replay spoiler-safe, order dinner on DoorDash, and invite my friends on Discord. Make it feel like a real experience without me needing to think.',
  normalized_intent:
    'Plan a game night: pick a free evening, set up a spoiler-safe FIFA replay, order dinner (DoorDash food), invite friends to your Discord group, and set reminders.',
  user_goal: 'Preserve and enrich a personal experience without effort — and without ever seeing the result early.',
  success_criteria: [
    'A free evening this week is chosen',
    'A spoiler-safe replay path (no score shown)',
    'A viewing setup + food plan',
    'Reminders + calendar block prepared',
  ],
  constraints: ['Spoiler-safe — never reveal the result', 'This week', 'At-home setup preferred'],
  time_window: 'A free evening this week',
  requested_capabilities: [
    'calendar.read',
    'sports.search.spoiler_safe',
    'streaming.search',
    'device.prepare.proposed',
    'food.recommend',
    'delivery.order.prepare',
    'reminders.write.proposed',
    'calendar.write.proposed',
  ],
  commit_capabilities: ['delivery.order.submit', 'social.post.commit', 'calendar.write.commit', 'reminders.write.commit'],
  budget_limit: { amount: 45, currency: 'USD' },
  ttl_seconds: 3600,
  risk_level: 'medium',
  fallback_plan:
    'Deny the order and Passport still gives you the full plan — you can order food yourself, or approve later. Nothing is bought without you.',
  prevented: [
    'Showing the final score (spoiler-safe mode held throughout)',
    'Placing a food order or charging a card without approval',
    'Messaging your Discord group without your explicit OK',
    'Taking live control of your TV',
    'Buying or renting streaming content',
  ],
  steps: [
    { kind: 'note', title: 'Read the emotional intent', description: 'You care about the game and cannot watch live — so the result must never leak, and the night should feel effortless.' },
    { kind: 'tool', title: 'Find a free evening', description: 'Scan the week for an open night.', tool: 'calendar.availability', input: {} },
    { kind: 'tool', title: 'Locate the game (spoiler-safe)', description: 'Pull game metadata without revealing the score.', tool: 'sports.find', input: {} },
    { kind: 'tool', title: 'Find spoiler-safe replay', description: 'Find replay options that won’t show the result.', tool: 'streaming.find', input: {} },
    { kind: 'tool', title: 'Plan the setup', description: 'Draft a TV hand-off plan. No device is touched.', tool: 'device.prepare', input: {} },
    { kind: 'tool', title: 'Plan food', description: 'Recommend a reorder from your history.', tool: 'food.recommend', input: {} },
    { kind: 'tool', title: 'Prepare the order', description: 'Build a delivery cart for review. Not ordered.', tool: 'delivery.prepare', input: {} },
    { kind: 'tool', title: 'Draft reminders', description: 'Propose reminders to start on time + avoid spoilers. Not set.', tool: 'reminders.propose', input: { items: ['Start the match replay at 7:00', 'Mute sports notifications until then'] } },
    { kind: 'tool', title: 'Draft the calendar block', description: 'Propose a "FIFA catch-up night" block. Not written.', tool: 'calendar.propose', input: { title: 'FIFA catch-up night', day: 'Thu', start: '18:30', end: '21:00' } },
    {
      kind: 'approval',
      title: 'Place the food order',
      description: 'Order the prepared cart and charge your card.',
      commitTool: 'delivery.submit',
      commitInput: { vendor: 'La Taqueria (DoorDash)' },
      packet: {
        action_type: 'Place delivery order',
        description: 'Order your usual from La Taqueria via DoorDash and pay with your saved Snaplii Cash — delivered to your home for kickoff.',
        external_party: 'DoorDash · La Taqueria',
        estimated_cost: { amount: 15, currency: 'USD' },
        data_shared: ['Delivery address', 'Order items', 'Your saved Snaplii Cash'],
        irreversible: true,
        approve_button_label: 'Approve & order',
        deny_button_label: "Don't order",
        capability: 'delivery.order.submit',
      },
    },
    {
      kind: 'approval',
      title: 'Invite your Game Night',
      description: 'Share the plan to your Discord — Game Night group.',
      commitTool: 'discord.post',
      commitInput: { channel: 'Game Night' },
      packet: {
        action_type: 'Message your Game Night group',
        description: 'Post the time + place to your Discord “Game Night” so your friends can join — place is your delivery address.',
        external_party: 'Discord · Game Night',
        estimated_cost: null,
        data_shared: ['Event time', 'Place (your delivery address)'],
        irreversible: true,
        approve_button_label: 'Send to Game Night',
        deny_button_label: "Don't share",
        capability: 'social.post.commit',
      },
    },
    {
      kind: 'approval',
      title: 'Block the calendar',
      description: 'Write the catch-up night to your calendar.',
      commitTool: 'calendar.commit',
      commitInput: { title: 'FIFA catch-up night' },
      packet: {
        action_type: 'Add calendar event',
        description: 'Add "FIFA catch-up night" to your calendar Thursday 6:30–9:00 PM.',
        external_party: null,
        estimated_cost: null,
        data_shared: ['Event title', 'Time'],
        irreversible: false,
        approve_button_label: 'Block the night',
        deny_button_label: 'Skip',
        capability: 'calendar.write.commit',
      },
    },
    {
      kind: 'approval',
      title: 'Set the reminders',
      description: 'Create the spoiler-safe reminders.',
      commitTool: 'reminders.commit',
      commitInput: {},
      packet: {
        action_type: 'Set reminders',
        description: 'Create 2 reminders: start the replay, and mute sports notifications until then.',
        external_party: null,
        estimated_cost: null,
        data_shared: ['Reminder text', 'Times'],
        irreversible: false,
        approve_button_label: 'Set reminders',
        deny_button_label: 'Skip',
        capability: 'reminders.write.commit',
      },
    },
  ],
  finalize(ctx: FinalizeContext) {
    return {
      title: 'Your FIFA catch-up night',
      summary: 'Thursday 6:30–9:00 PM — spoiler-safe replay, food, and reminders, ready to go.',
      lines: [
        line('Night', 'Thursday 6:30–9:00 PM', 'good'),
        line('Watch', 'Peacock full-match replay · spoiler-safe', 'good'),
        line('Result', 'Hidden — never shown', 'good'),
        line('Setup', 'Living-room Apple TV (proposed hand-off)'),
        line('Food', approvedCap(ctx, 'delivery.order.submit') ? 'Ordered · La Taqueria · paid via Snaplii' : 'Cart ready — not ordered', approvedCap(ctx, 'delivery.order.submit') ? 'good' : 'warn'),
        line('Friends', approvedCap(ctx, 'social.post.commit') ? 'Invited · Discord · Game Night' : 'Not shared', approvedCap(ctx, 'social.post.commit') ? 'good' : 'warn'),
        line('Calendar', approvedCap(ctx, 'calendar.write.commit') ? 'Blocked (simulated)' : 'Drafted — not written', approvedCap(ctx, 'calendar.write.commit') ? 'good' : 'warn'),
        line('Reminders', approvedCap(ctx, 'reminders.write.commit') ? 'Set (simulated)' : 'Drafted — not set', approvedCap(ctx, 'reminders.write.commit') ? 'good' : 'warn'),
      ],
      notes: [
        'Spoiler-safe mode held the entire time — the result was never surfaced.',
        'No money moved and no device was touched without your explicit approval.',
      ],
    }
  },
}
