import type { FinalizeContext, ScenarioSpec } from './types'
import { approvedCap, line, resultStr } from './helpers'

export const fillMyNight: ScenarioSpec = {
  id: 'fill-my-night',
  title: 'Fill My Night',
  tagline: 'Turn a free evening into a high-value build session — safely.',
  tools: [
    { name: 'Google Calendar', use: 'confirm 5–9 PM is free' },
    { name: 'Luma · Eventbrite', use: 'find a buildable hackathon' },
    { name: 'Maps', use: 'keep it near downtown SF' },
    { name: '1Password', use: 'scoped login to register', approval: true },
    { name: 'Contacts', use: 'hackmates in SF tonight' },
    { name: 'Messages', use: 'invite your hackmates', approval: true },
  ],
  prompt:
    'I am free tomorrow night from 5–9 PM. Find me a hackathon event in downtown San Francisco that I can attend and build at. Prefer events or organizers I have attended before. Help me register, add it to my calendar, prepare materials if any, and share it with my hackmates who are in SF tomorrow night.',
  normalized_intent: 'Find + prepare a buildable SF hackathon tomorrow 5–9 PM, register, add to calendar, share with nearby hackmates.',
  user_goal: 'Convert a free evening into a high-value professional + social build session with zero manual searching.',
  success_criteria: [
    'A buildable event that fits 5–9 PM and is close to downtown',
    'Registration prepared (not submitted) for review',
    'Calendar event drafted',
    'A message to nearby hackmates drafted',
  ],
  constraints: ['Tomorrow 17:00–21:00', 'Downtown SF', 'Prefer familiar organizers + buildable events'],
  time_window: 'Tomorrow 5:00–9:00 PM',
  requested_capabilities: [
    'calendar.read',
    'events.search',
    'location.estimate',
    'credential.scoped_request',
    'events.registration.prepare',
    'contacts.read.limited',
    'messages.draft',
    'calendar.write.proposed',
  ],
  commit_capabilities: ['events.registration.submit', 'calendar.write.commit', 'messages.send'],
  ttl_seconds: 3600,
  risk_level: 'medium',
  fallback_plan:
    'If you deny registration or sharing, Passport keeps the drafts and changes nothing externally; you can register or send later in one tap.',
  prevented: [
    'Registering you for an event before you saw it',
    'Reading your whole address book (only the "hackmates" group was read)',
    'Sending messages to contacts without your approval',
    'Exposing your event-site password to the agent',
  ],
  steps: [
    { kind: 'note', title: 'Understand the request', description: 'This is a multi-capability intent: discover, evaluate, prepare, and share — not just "find an event".' },
    { kind: 'tool', title: 'Check availability', description: 'Read calendar free/busy for tomorrow night.', tool: 'calendar.availability', input: { day: 'Tomorrow' } },
    { kind: 'tool', title: 'Infer preferences', description: 'Review previously attended events to learn what you like.', tool: 'history.attended', input: {} },
    { kind: 'tool', title: 'Discover events', description: 'Search Luma / Eventbrite / Meetup for tomorrow night.', tool: 'events.search', input: { day: 'Tomorrow' } },
    { kind: 'tool', title: 'Rank + recommend', description: 'Score by familiarity, buildability, fit, and travel time.', tool: 'events.rank', input: { day: 'Tomorrow' } },
    { kind: 'tool', title: 'Check feasibility', description: 'Estimate travel from your hackathon to the venue.', tool: 'location.travel', input: { event_id: 'ev_1' } },
    { kind: 'tool', title: 'Broker a scoped login', description: 'Request a scoped, opaque handle to your event-site login. The agent never sees the password.', tool: 'credential.request', input: { item_ref: 'op://Personal/luma-account' } },
    { kind: 'tool', title: 'Prepare registration', description: 'Draft the registration for review. Not submitted.', tool: 'registration.prepare', input: { event_id: 'ev_1' } },
    { kind: 'tool', title: 'Read hackmates (limited)', description: 'Read only the "hackmates" group to find who is in SF tomorrow night.', tool: 'contacts.hackmates', input: {} },
    { kind: 'tool', title: 'Draft share message', description: 'Compose a message to nearby hackmates. Not sent.', tool: 'messages.draft', input: { to: 'hackmates (3 in SF)', body: 'Building at the AGI House Agent Security & Identity night tomorrow 5:30–9. Come build? I can save seats.' } },
    { kind: 'tool', title: 'Draft calendar event', description: 'Propose a calendar block. Not written.', tool: 'calendar.propose', input: { title: 'AGI House — Agent Security & Identity Build Night', day: 'Tomorrow', start: '17:30', end: '21:00' } },
    {
      kind: 'approval',
      title: 'Approve registration',
      description: 'Register you for the event on the external site.',
      commitTool: 'registration.submit',
      commitInput: { event: 'AGI House — Agent Security & Identity Build Night' },
      packet: {
        action_type: 'Register for event',
        description: 'Submit your registration to AGI House (via Luma) for the Agent Security & Identity Build Night.',
        external_party: 'Luma / AGI House',
        estimated_cost: null,
        data_shared: ['Name', 'Role: Builder', 'Team size'],
        irreversible: false,
        approve_button_label: 'Approve & register',
        deny_button_label: "Don't register",
        capability: 'events.registration.submit',
      },
    },
    {
      kind: 'approval',
      title: 'Add to calendar',
      description: 'Write the event to your personal calendar.',
      commitTool: 'calendar.commit',
      commitInput: { title: 'AGI House — Agent Security & Identity Build Night' },
      packet: {
        action_type: 'Add calendar event',
        description: 'Add "AGI House — Agent Security & Identity Build Night" to your Personal calendar tomorrow 5:30–9:00 PM.',
        external_party: null,
        estimated_cost: null,
        data_shared: ['Event title', 'Time'],
        irreversible: false,
        approve_button_label: 'Add to calendar',
        deny_button_label: 'Skip',
        capability: 'calendar.write.commit',
      },
    },
    {
      kind: 'approval',
      title: 'Send to hackmates',
      description: 'Send the drafted message to your 3 nearby hackmates.',
      commitTool: 'messages.send',
      commitInput: { to: 'hackmates (3 in SF)' },
      packet: {
        action_type: 'Send message to hackmates',
        description: 'Send your drafted invite to Ari, Jules, and Devi (in SF tomorrow night).',
        external_party: 'Ari, Jules, Devi',
        estimated_cost: null,
        data_shared: ['Event name', 'Time', 'Your note'],
        irreversible: true,
        approve_button_label: 'Send invite',
        deny_button_label: "Don't send",
        capability: 'messages.send',
      },
    },
  ],
  finalize(ctx: FinalizeContext) {
    const rec = (ctx.results['events.rank']?.data?.recommended ?? {}) as Record<string, unknown>
    const travel = resultStr(ctx.results['location.travel'], 'feasible travel')
    return {
      title: 'Tonight’s build plan',
      summary: `${String(rec.title ?? 'AGI House Build Night')} — ${String(rec.start ?? '17:30')}–${String(rec.end ?? '21:00')} in ${String(rec.neighborhood ?? 'SoMa, SF')}.`,
      lines: [
        line('Event', String(rec.title ?? 'AGI House — Agent Security & Identity Build Night'), 'good'),
        line('Organizer', `${String(rec.organizer ?? 'AGI House')} · familiar`),
        line('Travel', travel),
        line('Registration', approvedCap(ctx, 'events.registration.submit') ? 'Registered (simulated)' : 'Drafted — not submitted', approvedCap(ctx, 'events.registration.submit') ? 'good' : 'warn'),
        line('Calendar', approvedCap(ctx, 'calendar.write.commit') ? 'Added (simulated)' : 'Drafted — not written', approvedCap(ctx, 'calendar.write.commit') ? 'good' : 'warn'),
        line('Hackmates', approvedCap(ctx, 'messages.send') ? 'Invite sent (simulated)' : 'Draft ready — not sent', approvedCap(ctx, 'messages.send') ? 'good' : 'warn'),
        line('Credentials', 'Scoped handle only — password never exposed', 'good'),
      ],
      notes: [
        'Everything external was prepared first and only happened after you approved it.',
        'The grant is still revocable and expires in 60 minutes.',
      ],
    }
  },
}
